# Generated by Django 4.1.2 on 2022-12-14 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_order_dishes_order_dishes'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='id_user',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
